In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("amazon_india_complete_2015_2025.csv")
df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2023_00063013,2023-07-23,CUST_2023_00018393,PROD_000454,Vivo Y95 64GB Black,Electronics,Smartphones,Vivo,27340.84,21.57,...,False,NaN,4.0,Delivered,7,2023,3,0.20,True,3.5
1,TXN_2021_00064486,20-07-2021,CUST_2015_00002865,PROD_000579,Realme Realme 3 128GB Black,Electronics,Smartphones,Realme,32907.49,0.00,...,False,NaN,5/5,Delivered,7,2021,3,0.21,False,4.5
2,TXN_2017_00065617,2017-11-16,CUST_2016_00004057,PROD_000295,Vivo V7 32GB Blue,Electronics,Smartphones,Vivo,"47,052.18",21.91,...,False,NaN,5.0,Delivered,11,2017,4,0.24,True,4.3
3,TXN_2020_00054393,2020-05-04,CUST_2020_00014574,PROD_001654,Alienware Pavilion 4GB RAM Silver,Electronics,Laptops,Alienware,238725.44,59.60,...,True,Summer Sale,5.0 stars,Delivered,5,2020,2,1.85,Yes,3.6
4,TXN_2018_00071646,2018-10-09,CUST_2018_00006275,PROD_000095,Motorola Moto X Play 16GB White,Electronics,Smartphones,Motorola,25970.76,0.00,...,False,NaN,4.0,Delivered,10,2018,4,0.16,False,3.7

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  object
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  float64
 10  discounted_price_inr    1127609 non-null  float64
 11  quantity                1127609 non-null  int64
 12  subtotal_inr            1127609 non-null  float64
 13  delivery_charges        1037408 non-null  float64
 14  final_amount_inr        1127609 non-null  float64
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int64
 29  order_year              1127609 non-null  int64
 30  order_quarter           1127609 non-null  int64
 31  product_weight_kg       1127609 non-null  float64
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  float64
dtypes: float64(7), int64(4), object(23)
memory usage: 292.5+ MB

In [3]:
df.isnull().sum()

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           90201
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        135315
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             777736
customer_rating           341696
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

In [4]:
df.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'subcategory', 'brand',
       'original_price_inr', 'discount_percent', 'discounted_price_inr',
       'quantity', 'subtotal_inr', 'delivery_charges', 'final_amount_inr',
       'customer_city', 'customer_state', 'customer_tier',
       'customer_spending_tier', 'customer_age_group', 'payment_method',
       'delivery_days', 'delivery_type', 'is_prime_member', 'is_festival_sale',
       'festival_name', 'customer_rating', 'return_status', 'order_month',
       'order_year', 'order_quarter', 'product_weight_kg', 'is_prime_eligible',
       'product_rating'],
      dtype='object')

Question 1
Your dataset contains order_date in multiple formats: 'DD/MM/YYYY', 'DD-MM-YY', 'YYYY-MM-DD', and some invalid entries like '32/13/2020'. Clean and standardize all dates to 'YYYY-MM-DD' format, handling invalid dates appropriately.

In [5]:
df['order_date'] = pd.to_datetime(
    df['order_date'], 
    errors='coerce',     # turn bad ones into NaT
    dayfirst=True,       # needed for DD-MM-YYYY and DD/MM/YYYY
    format="mixed"       # <-- NEW in Pandas 2.0, handles mixed styles
)

In [6]:
df.shape

(1127609, 34)

Question 2
The original_price_inr column contains mixed data types: numeric values, text with '₹' symbols, comma separators ('₹1,25,000'), and some entries like 'Price on Request'. Clean this column to contain only numeric values in Indian Rupees.

In [7]:
df["original_price_inr"] = (
    df["original_price_inr"]
    .astype(str)                  
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("Rs", "", regex=False)
)
df['original_price_inr'] = pd.to_numeric(
    df['original_price_inr'], errors='coerce'
)

df["original_price_inr"] = df["original_price_inr"].abs()

In [8]:
df.shape

(1127609, 34)

Question 3
Customer ratings appear in various formats: '5.0', '4 stars', '3/5', '2.5/5.0', and some missing values. Standardize all ratings to numeric scale 1.0-5.0, handling inconsistent formats and missing values strategically.

In [9]:
df['customer_rating'] = (
    df['customer_rating']
    .astype(str)
    .str.lower()
    .str.strip()
    .str.replace('stars', '', regex=False)
    .str.replace('star', '', regex=False)
)

In [10]:
def convert_fraction_rating(x):
    if '/' in x:
        try:
            num, den = x.split('/')
            return (float(num) / float(den)) * 5
        except:
            return np.nan
    return x

In [11]:
df['customer_rating'] = (
    df['customer_rating']
    .apply(convert_fraction_rating)
)

In [12]:
df['customer_rating'] = pd.to_numeric(
    df['customer_rating'],
    errors='coerce'
)

In [13]:
len(df)

1127609

In [14]:
missing_pct = (
    df['customer_rating'].isna().mean() * 100
)
print(f"Missing Ratings: {missing_pct:.2f}%")

Missing Ratings: 30.30%

In [15]:
df['customer_rating'] = (
    df
    .groupby('category')['customer_rating']
    .transform(lambda x: x.fillna(x.median()))
)

In [16]:
df.shape

(1127609, 34)

Question 4
The customer_city column has inconsistent naming: 'Bangalore/Bengaluru', 'Mumbai/Bombay', 'Delhi/New Delhi', along with spelling errors and case variations. Standardize all city names and handle geographical variations.

In [17]:
city_map = {
    # Bengaluru
    'bangalore': 'Bangalore',
    'bengalore': 'Bangalore',
    'BANGALORE': 'Bangalore',
    'banglore': 'Bangalore',
    'bengaluru': 'Bangalore',

    # Mumbai
    'mumbai': 'Mumbai',
    'mumba': 'Mumbai',
    'bombay': 'Mumbai',
    'Mumbai ': 'Mumbai',
    'Bombay': 'Mumbai',
    'MUMBAI': 'Mumbai',

    # Delhi
    'delhi': 'Delhi',
    'new delhi': 'Delhi',
    'delhi ncr': 'Delhi',
    'DELHI': 'Delhi',

    # Chennai
    'chennai': 'Chennai',
    'chenai': 'Chennai',
    'madras': 'Chennai',
    'CHENNAI': 'Chennai',
    'Madras': 'Chennai',
    'Chennai ': 'Chennai',

    # Kolkata
    'KOLKATA': 'Kolkata',
    'kolkata': 'Kolkata',
    'calcutta': 'Kolkata'

}
df['customer_city'] = (
    df['customer_city']
    .str.lower()
    .str.strip()
    .replace(city_map)
    .str.title()
)

In [18]:
df.shape

(1127609, 34)

Question 5
Boolean columns (is_prime_member, is_prime_eligible, is_festival_sale) contain mixed values: True/False, Yes/No, 1/0, Y/N, and some missing entries. Convert all boolean columns to consistent True/False format.

In [19]:
bool_map = {
    'yes': True, 'y': True, '1': True, 'true': True,
    'no': False, 'n': False, '0': False, 'false': False
}

bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

for col in bool_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.lower()
        .map(bool_map)
    )

In [20]:
df.shape

(1127609, 34)

Question 6
Product categories have variations: 'Electronics/Electronic/ELECTRONICS/Electronics & Accessories'. Standardize category names across the dataset and ensure consistent naming conventions.

In [21]:
category_map = {
    'electronics': 'Electronics',
    'electronic': 'Electronics',
    'electronicss': 'Electronics',
    'ELECTRONICS': 'Electronics',
    'electronics & accessories': 'Electronics'
}
df['category'] = (
    df['category']
    .str.lower()
    .str.strip()
    .replace(category_map)
    .str.title()
)

In [22]:
df.shape

(1127609, 34)

Question 7
The delivery_days column contains negative values, text entries like 'Same Day', '1-2 days', and some unrealistic values like 50 days. Clean this column to contain only valid numeric delivery days.

In [23]:
df['delivery_days'].value_counts()
#df["delivery_days"].isna().sum()

delivery_days
3           288488
1           210462
4           206438
5           136608
2           126280
6           102668
7            34116
-1            6836
1-2 days      4534
Same Day      4469
Express       2317
0             2218
15            2175
Name: count, dtype: int64

In [24]:
df['delivery_days'] = df['delivery_days'].replace({
    'Same Day': 0,
    '1-2 days': 2,
    'Express': 1,
    "-1": 0,
})




df['delivery_days'].isnull().sum()

np.int64(0)

In [25]:
df["delivery_days"] = pd.to_numeric(
    df["delivery_days"],
    errors="coerce"
)
df["delivery_days"] = df["delivery_days"].astype("Int64")

In [26]:
df['delivery_days'].value_counts()

delivery_days
3     288488
1     212779
4     206438
5     136608
2     130814
6     102668
7      34116
0      13523
15      2175
Name: count, dtype: Int64

In [27]:
df.shape

(1127609, 34)

Question 8
Identify and handle duplicate transactions where the same customer, product, date, and amount appear multiple times. Some duplicates are genuine (bulk orders) while others are data errors. Develop a strategy to distinguish and handle both cases.

In [28]:
df.duplicated().sum()
df.duplicated(subset=['transaction_id']).sum()

np.int64(0)

In [29]:
df = df[~df["transaction_id"].str.contains("_DUP", na=False)]

In [30]:
df.shape

(1122000, 34)

Question 9
The dataset contains outlier prices where some products show prices 100x higher than expected due to data entry errors (decimal point issues). Identify and correct these outliers using statistical methods and domain knowledge.

In [31]:
df["product_mean_price"] = (
    df.groupby("product_id")["original_price_inr"]
    .transform("mean")
)

In [32]:
df["original_price_inr"].max()

np.float64(33371693.0)

In [33]:
df["product_mean_price"].isna().sum()

np.int64(0)

In [34]:
pd.set_option("display.max_rows", None)
print(df.loc[
    df["original_price_inr"] > 200000,
    ["product_name", "original_price_inr"]
])

                                    product_name  original_price_inr
3              Alienware Pavilion 4GB RAM Silver           238725.44
22           Apple iPhone 13 Pro Max 256GB White           392777.17
38              Alienware MacBook 4GB RAM Silver           227208.08
60                              LG 4K TV Premium           221436.39
105              Apple iPhone 13 mini 64GB White           213909.05
189                   HP Inspiron 4GB RAM Silver           206655.37
210              Apple iPhone XS Max 256GB Black           238086.62
248                    Apple iPhone 15 64GB Gold           262527.62
259                     Samsung Smart TV Premium           647713.50
274                    Apple iPhone 6 16GB White           238513.74
301                Apple iPhone 11 Pro 64GB Blue           245823.33
325                   Noise Sports Watch Premium          4631753.00
330                     Apple iPhone X 16GB Blue           238760.02
352              Apple iPhone XS Max 256GB Black           238086.62
373                   Apple iPhone XR 128GB Blue           234876.44
379           Apple iPhone 13 Pro Max 64GB Black           328204.91
380                   MSI Inspiron 4GB RAM Black           277299.57
449                    Apple iPhone 6 16GB Black           224159.47
462                   Apple iPhone 5s 32GB Black           248193.42
476                                   LG QLED TV           482720.90
514             Apple iPhone 13 mini 256GB White           420704.77
524                    HP Inspiron 8GB RAM Black           220127.27
529               Apple iPhone 7 Plus 32GB White           232691.77
532                   Apple iPhone 5s 32GB Black           239021.02
547                 Samsung Galaxy S8 32GB Black           206649.13
548                                Samsung 4K TV         13099514.00
551                 ASUS Ultrabook 8GB RAM Black           223131.55
626              Apple iPhone 12 Pro 256GB Black           263918.91
629              Apple iPhone 15 Pro 128GB White           264588.38
637            Alienware Pavilion 4GB RAM Silver           200189.05
658            OnePlus OnePlus 9 Pro 128GB White          6892693.00
681                   Apple iPhone 13 128GB Blue           301886.54
682                  Apple iPhone 12 128GB Black           239133.77
731                   Apple iPhone 13 128GB Blue           324415.99
747                  Apple iPhone XR 128GB White           205786.85
766               Apple iPhone 12 Pro 64GB Black           278244.91
811                                  LG Smart TV           213971.91
887                  Apple iPhone 11 256GB White           250958.25
916                 Lenovo Tab M10 8GB RAM Black           563378.90
939                   Apple iPhone XR 128GB Blue           260406.22
945           Apple iPhone 11 Pro Max 64GB White           261589.00
956              Apple iPhone 14 Pro 256GB White           241623.23
1046                 ASUS Pavilion 4GB RAM Black           243811.66
1058            Samsung Galaxy Note 9 64GB Black           208210.59
1061                   Apple iPhone 6 16GB White           212889.01
1074          Apple iPhone 12 Pro Max 64GB Black           285360.37
1204                  Dell MacBook 4GB RAM Black           234120.28
1218                       Samsung 4K TV Premium           208200.42
1230                Samsung Galaxy S7 32GB White           200174.60
1270           OnePlus Galaxy Tab 4GB RAM Silver          9217160.00
1281                  Apple iPhone 13 64GB Black           290439.23
1295                  Xiaomi Poco F5 256GB Black           333591.00
1330                  MSI Inspiron 4GB RAM Black           280289.33
1340               Apple iPhone 8 Plus 64GB Blue           251083.57
1351                  Apple iPhone XS 256GB Blue           252971.00
1408             Apple iPhone 13 mini 128GB Blue           200405.96
1419           Alienware Pavilion 4GB RAM Silver           200189.05
1438                  Dell MacBook 4GB RAM Black           234120.28
1460               Samsung Galaxy S20+ 64GB Blue           204873.32
1499                      Samsung OLED TV Deluxe           223378.34
1507               Apple iPhone 6 Plus 16GB Blue           220350.00
1559           Samsung Galaxy S6 Edge 32GB White         19766006.00
1629               Samsung Galaxy S20+ 64GB Blue           204873.32
1646           Alienware Ultrabook 4GB RAM Black          1217343.30
1678                         Noise Watch Premium          4750248.00
1684             Apple iPhone 15 Plus 64GB White           201314.40
1733             Apple iPhone 13 Pro 128GB Black           244463.83
1816                            Samsung Smart TV           242429.10
1910              Apple iPhone 6 Plus 16GB Black         13427816.00
1936                  Apple iPhone XR 128GB Blue           234876.44
2031                   Apple iPhone 8 16GB Black           237677.27
2045                    Apple iPhone 6 16GB Blue           216501.02
2078                  Apple iPhone XR 64GB White           213548.22
2148            Motorola Moto G4 Plus 32GB Black           246718.70
2150                   Apple iPhone 14 64GB Blue           233047.89
2153                  Apple iPhone XS 256GB Blue           262678.23
2161                  Apple iPhone 13 256GB Blue           278477.90
2168                 Apple iPhone 14 256GB Black           253252.99
2181                  Apple iPhone 13 128GB Blue           410344.51
2183                   Apple iPhone 6 16GB Black           214572.30
2249              Samsung Galaxy A50 128GB White          3797254.00
2257                Dell Ultrabook 4GB RAM Black           256596.35
2258           Alienware Ultrabook 8GB RAM Black           216402.52
2321                 Apple iPhone 12 128GB White           224185.39
2323                 Acer ThinkPad 4GB RAM Black           207666.81
2327                Apple ThinkPad 4GB RAM Black           243305.41
2414                 Acer ThinkPad 4GB RAM Black           247059.98
2457                   HP Inspiron 8GB RAM Black           208429.21
2506             Apple iPhone 15 Pro 128GB White           291804.40
2528              Apple iPhone 8 Plus 64GB White           209264.14
2544            Apple iPhone 14 Plus 128GB Black           303416.41
2545              Lenovo Inspiron 4GB RAM Silver          1408104.10
2597                    Apple iPhone X 16GB Blue           204138.40
2629                 Apple iPhone 15 128GB White           233626.32
2664          Apple iPhone 12 Pro Max 256GB Blue           251174.69
2713                   Apple iPhone 8 64GB Black         13042700.00
2720                  Apple iPhone 14 128GB Blue           221353.78
2723            Apple iPhone 15 Plus 128GB White           261775.20
2779             Apple iPhone 12 Pro 128GB Black           214557.42
2783         Apple iPhone 13 Pro Max 128GB White           231398.18
2841           Audio-Technica Headphones Premium           226333.00
2848                   Apple iPhone 6 16GB White           218404.89
2908                         Garmin Watch Deluxe          5676636.00
2966                OnePlus OnePlus 6 64GB Black           541258.40
2973                 Apple iPhone 14 256GB White           300374.78
2977                Lenovo MacBook 4GB RAM Black           212233.00
3011               OnePlus OnePlus 3T 16GB White          9622171.00
3148                 OnePlus OnePlus 5 32GB Blue           514790.10
3187                   Apple iPhone 7 16GB White           203723.34
3246                  Apple iPhone XR 128GB Blue           260406.22
3280                   Apple iPhone 6 16GB Black           224159.47
3332           Samsung Galaxy Note 9 256GB Black           202470.20
3373                  Apple iPhone 13 128GB Blue           410344.51
3374                            Samsung Smart TV           259218.76
3382             Apple iPhone 14 Pro 128GB White           222786.72
3447             Alienware Gaming 8GB RAM Silver           218988.47
3449         Apple iPhone 12 Pro Max 128GB Black           269924.00
3480                 Apple iPhone 14 256GB Black           253253.00
3549         Apple iPhone 11 Pro Max 256GB White           252639.30
3558           Apple iPhone 11 Pro Max 64GB Blue           222109.80
3587                  Xiaomi Fitness Band Deluxe          2663953.00
3648           Samsung Galaxy Note 10 64GB White           212448.93
3705         Apple iPhone 15 Pro Max 128GB White           282113.77
3711                    Apple iPhone X 32GB Blue           210618.95
3800             Apple iPhone XS Max 256GB White           225472.74
3824                  Samsung Android TV Premium           326569.59
3903              Apple iPhone 12 Pro 64GB Black           211849.00
4001                    Apple iPhone X 16GB Blue           238760.02
4007                  Apple iPhone XR 128GB Blue           260406.22
4013              Apple iPhone 13 Pro 64GB Black           252216.76
4138                  Motorola Moto Z 32GB Black           245521.10
4148              Lenovo VivoBook 4GB RAM Silver           281012.18
4155                 Apple iPhone 16 128GB Black           231187.83
4162             Alienware Gaming 8GB RAM Silver           218988.47
4196                         Garmin Watch Deluxe           567663.60
4207                         Vivo V15 64GB Black          3067827.00
4222          Apple iPhone 13 Pro Max 128GB Blue           316731.81
4257                MSI Ultrabook 8GB RAM Silver           204970.55
4272            Apple iPhone 14 Plus 128GB Black           223760.87
4314                   Apple iPhone XR 64GB Blue           250018.22
4318              Apple iPhone XS Max 128GB Blue           235662.54
4334                          LG OLED TV Premium           234409.14
4416                          LG OLED TV Premium           251062.95
4459                            LG 4K TV Premium           300102.68
4500         Apple iPhone 11 Pro Max 256GB White           252639.30
4520                            LG 4K TV Premium           287334.40
4560             Apple iPhone 14 Pro 128GB White           245702.95
4592               Apple iPhone 8 Plus 64GB Blue           241804.36
4621              Samsung Galaxy M31 128GB Black          1296154.00
4685              Apple iPhone 7 Plus 32GB White           239273.00
4690           OnePlus OnePlus 8 Pro 128GB Black          5163305.00
4703            Samsung Galaxy Note 9 64GB Black           208210.59
4705              Apple iPhone 14 Pro 64GB White           246107.00
4708                 Apple iPhone 15 128GB White           204195.61
4745             Apple iPhone 12 Pro 128GB Black           206628.10
4815                ASUS Inspiron 4GB RAM Silver           221809.01
4837             Apple iPhone XS Max 256GB Black           274094.96
4851               Samsung Galaxy S21 64GB Black           221250.94
4900              Apple iPhone 7 Plus 32GB White           243088.52
4926                            LG 4K TV Premium           302960.80
4975         Apple iPhone 13 Pro Max 256GB Black           328886.18
4978                   Apple iPhone X 32GB White           245745.33
5147                Acer Pavilion 8GB RAM Silver           214183.88
5171               Apple iPhone 8 Plus 16GB Blue           233049.00
5172                Lenovo MacBook 4GB RAM Black           200954.22
5236                   Apple iPhone 8 64GB White           205782.04
5260                Samsung Galaxy S6 64GB White           223321.28
5312            Apple iPhone 13 mini 256GB White           309508.50
5315                   HP Inspiron 8GB RAM Black           209381.47
5353                 ASUS Pavilion 4GB RAM Black           243811.66
5401                  Apple iPhone 5s 16GB White         17458626.00
5404                     Oppo F3 Plus 16GB Black          3278456.00
5441              Apple iPhone 6 Plus 32GB White          1520150.20
5466               Samsung Galaxy S21 64GB Black           221250.94
5508             Apple iPhone 15 Plus 64GB White           201314.40
5513               Apple iPhone 11 Pro 64GB Blue           287514.67
5518            Apple iPhone 14 Plus 128GB Black           256011.52
5539                 Apple iPhone 14 256GB Black           272153.00
5561                                    LG 4K TV           238554.00
5579               OnePlus OnePlus 6T 64GB Black          8103463.00
5589                Samsung Galaxy S6 16GB Black          1454793.10
5632            Apple iPhone 13 mini 128GB White           410904.32
5662                  Realme Slate 4GB RAM Black           323604.60
5676         Apple iPhone 13 Pro Max 128GB White           264749.59
5712              Alienware Gaming 8GB RAM Black           210283.15
5770                  Apple iPhone 5s 16GB Black           219778.44
5782             Apple iPhone 15 Pro 128GB White           237513.52
5854                   Apple iPhone 15 64GB Gold           262527.62
5897                   Apple iPhone 6 16GB Black           224159.47
5898            Samsung Galaxy J7 Max 32GB Black          3276856.00
5932            Samsung Galaxy S7 Edge 32GB Gold          1064855.70
5936                    Apple iPhone 7 16GB Blue         11994017.00
5995                   Apple iPhone X 32GB White           255175.77
6025                ASUS Ultrabook 8GB RAM Black           205287.74
6129                 Apple Gaming 8GB RAM Silver           240130.56
6149                Acer Pavilion 8GB RAM Silver           233350.01
6151             Apple iPhone 13 Pro 128GB Black           244463.83
6175            Alienware Inspiron 4GB RAM Black           209726.87
6183              Lenovo VivoBook 4GB RAM Silver           284041.96
6195               Lenovo Tab M10 4GB RAM Silver          7262453.00
6273                Lenovo Tab M10 8GB RAM Black           999594.00
6275              Apple iPhone 7 Plus 16GB White           234092.52
6368                ASUS Ultrabook 8GB RAM Black           223131.55
6435              Xiaomi Redmi Note 4 32GB Black          1604591.00
6442                    Apple iPhone 6 16GB Blue           284354.74
6475                   Xiaomi Poco F6 64GB White           291206.80
6550              Apple iPhone XS Max 64GB Black           222416.78
6556               OnePlus OnePlus 3T 32GB White         11046013.00
6638                  MSI Inspiron 8GB RAM Black           208698.51
6665            Apple iPhone 14 Plus 128GB Black           256011.52
6844                 Apple iPhone 12 128GB White           224185.39
6857                        Xiaomi Watch Premium          4645894.00
6925               Apple iPhone 11 Pro 64GB Blue           276889.09
6973            Alienware Inspiron 4GB RAM Black           262934.79
6977              Samsung Galaxy S10+ 64GB Black         10400687.00
6982               Apple iPhone 8 Plus 16GB Blue           202432.70
7028               Samsung Galaxy S23 64GB White           672151.00
7032                 Apple iPhone 14 256GB White           253445.10
7043               Nothing Phone (3) 128GB White          1667281.00
7071                   Apple iPhone 8 64GB White           240682.42
7081              Apple iPhone 7 Plus 64GB Black           213831.60
7135                                    LG 4K TV           245965.02
7139           Samsung Galaxy S7 Edge 32GB White           228761.54
7266                    Apple iPhone X 16GB Blue           238760.00
7292                  MSI Inspiron 4GB RAM Black           235043.46
7368               Apple iPhone 6 Plus 16GB Blue           244300.62
7378                 Acer ThinkPad 4GB RAM Black           200486.43
7387                            LG 4K TV Premium           287334.40
7388             Lenovo Ultrabook 4GB RAM Silver           217103.31
7389                Apple Pavilion 4GB RAM Black           227739.48
7420           OnePlus OnePlus 7 Pro 128GB Black          6728829.00
7441              Apple iPhone 7 Plus 32GB White           239272.95
7482                    Apple iPhone X 32GB Blue           204825.90
7485                            LG 4K TV Premium           287334.40
7497                Samsung Galaxy S6 16GB White           208432.22
7500             Apple iPhone 13 Pro 128GB Black           289730.48
7525                Apple ThinkPad 4GB RAM Black           203132.08
7530              Apple iPhone 8 Plus 64GB White           251677.45
7542                 Apple iPhone 15 128GB White           257657.53
7580           Apple iPhone 11 Pro Max 64GB Blue           230633.23
7587          Apple iPhone 13 Pro Max 128GB Blue           267246.55
7592            Apple iPhone 13 mini 128GB White           410904.32
7671          Apple iPhone 13 Pro Max 64GB White           202968.61
7743                Dell Ultrabook 4GB RAM Black           256596.35
7965                 Apple Gaming 8GB RAM Silver           245284.15
8031               Apple Pavilion 4GB RAM Silver           213116.42
8148              Apple iPhone XS Max 128GB Blue           212558.59
8170             Motorola Moto G4 Plus 32GB Blue           234113.20
8196          Apple iPhone 13 Pro Max 128GB Blue           316731.81
8200                Samsung Fitness Band Premium          3594530.00
8201                    Apple iPhone 7 16GB Gold         13136082.00
8204                 Dell Pavilion 4GB RAM Black           242116.67
8210         Apple iPhone 13 Pro Max 128GB White           396881.85
8258                OnePlus OnePlus 2 16GB Black          7153369.00
8337                                    LG 4K TV           245965.02
8364                    Apple iPhone X 32GB Blue           210618.95
8391              Apple iPhone 12 Pro 64GB Black           278244.91
8425                 Apple iPhone 11 128GB Black           241794.64
8575                  MSI Inspiron 4GB RAM Black           216247.05
8617         Apple iPhone 15 Pro Max 256GB White           265408.48
8630               Apple iPhone 15 Pro 64GB Blue           309077.73
8634                          LG OLED TV Premium           234409.00
8657                  Audio-Technica TWS Premium          2029027.00
8662                Lenovo Gaming 4GB RAM Silver           788597.90
8726                  Apple iPhone XR 64GB White           245845.36
8734                   Xiaomi iPad 4GB RAM Black           558113.00
8785                  Samsung Android TV Premium           305463.30
8786             Samsung Galaxy Note 5 16GB Gold           204938.11
8932                     Xiaomi Mi 10 64GB Black          1006905.00
8940                     Oppo Reno 6 128GB Black          5211607.00
8952         Apple iPhone 14 Pro Max 128GB White           249342.11
8990                Apple ThinkPad 4GB RAM Black           203132.08
9040                    Apple iPhone 7 16GB Gold          1748272.10
9070                            LG 4K TV Premium           287334.40
9089              Apple iPhone XS Max 64GB Black           218925.68
9093                   Apple iPhone 8 16GB Black           237677.27
9101           Samsung Galaxy S7 Edge 32GB White           228761.54
9116               Nothing Phone (3) 256GB White           281278.80
9124                   Apple iPhone 6 32GB Black           206713.04
9127                 Realme Realme 1 128GB Black          2913876.00
9169                 Dell Pavilion 4GB RAM Black           239534.09
9329                                    LG 4K TV           251527.09
9372             Apple iPhone 14 Pro 128GB White           264039.48
9487                 ASUS Pavilion 4GB RAM Black           243811.66
9537                 Apple iPhone XS 256GB White           217991.48
9553                            Samsung Smart TV           250879.79
9565                    Apple iPhone 7 16GB Gold           204477.69
9587                   Apple iPhone 8 32GB White         14396134.00

In [35]:
threshold = 1.1


df["original_price_inr"] = df["original_price_inr"].where(
    df["original_price_inr"] <= threshold * df["product_mean_price"],
    df["product_mean_price"]
)

In [36]:
df["original_price_inr"].describe()

count    1.122000e+06
mean     6.550130e+04
std      5.052344e+04
min      1.067270e+03
25%      2.879170e+04
50%      4.614487e+04
75%      9.287530e+04
max      8.955562e+05
Name: original_price_inr, dtype: float64

In [37]:
pd.set_option("display.max_rows", None)
print(df.loc[
    df["original_price_inr"] > 200000,
    ["product_name", "original_price_inr"]
])

                                 product_name  original_price_inr
3           Alienware Pavilion 4GB RAM Silver       208663.542648
22        Apple iPhone 13 Pro Max 256GB White       309308.784240
60                           LG 4K TV Premium       221436.390000
105           Apple iPhone 13 mini 64GB White       213909.050000
210           Apple iPhone XS Max 256GB Black       238086.620000
248                 Apple iPhone 15 64GB Gold       262527.620000
274                 Apple iPhone 6 16GB White       238513.740000
301             Apple iPhone 11 Pro 64GB Blue       245823.330000
330                  Apple iPhone X 16GB Blue       238760.020000
352           Apple iPhone XS Max 256GB Black       238086.620000
373                Apple iPhone XR 128GB Blue       234876.440000
379        Apple iPhone 13 Pro Max 64GB Black       328204.910000
380                MSI Inspiron 4GB RAM Black       277299.570000
449                 Apple iPhone 6 16GB Black       224159.470000
462                Apple iPhone 5s 32GB Black       203083.108838
514          Apple iPhone 13 mini 256GB White       329841.473173
524                 HP Inspiron 8GB RAM Black       220127.270000
529            Apple iPhone 7 Plus 32GB White       232691.770000
532                Apple iPhone 5s 32GB Black       203083.108838
547              Samsung Galaxy S8 32GB Black       206649.130000
551              ASUS Ultrabook 8GB RAM Black       223131.550000
626           Apple iPhone 12 Pro 256GB Black       263918.910000
629           Apple iPhone 15 Pro 128GB White       264588.380000
637         Alienware Pavilion 4GB RAM Silver       200189.050000
681                Apple iPhone 13 128GB Blue       301886.540000
682               Apple iPhone 12 128GB Black       239133.770000
731                Apple iPhone 13 128GB Blue       324415.990000
766            Apple iPhone 12 Pro 64GB Black       248519.573956
811                               LG Smart TV       213971.910000
887               Apple iPhone 11 256GB White       250958.250000
939                Apple iPhone XR 128GB Blue       260406.220000
945        Apple iPhone 11 Pro Max 64GB White       261589.000000
956           Apple iPhone 14 Pro 256GB White       241623.230000
1046              ASUS Pavilion 4GB RAM Black       243811.660000
1058         Samsung Galaxy Note 9 64GB Black       208210.590000
1061                Apple iPhone 6 16GB White       212889.010000
1074       Apple iPhone 12 Pro Max 64GB Black       237842.802760
1204               Dell MacBook 4GB RAM Black       234120.280000
1230             Samsung Galaxy S7 32GB White       200174.600000
1281               Apple iPhone 13 64GB Black       237991.813033
1330               MSI Inspiron 4GB RAM Black       280289.330000
1340            Apple iPhone 8 Plus 64GB Blue       216876.158706
1351               Apple iPhone XS 256GB Blue       252971.000000
1408          Apple iPhone 13 mini 128GB Blue       200405.960000
1419        Alienware Pavilion 4GB RAM Silver       200189.050000
1438               Dell MacBook 4GB RAM Black       234120.280000
1499                   Samsung OLED TV Deluxe       223378.340000
1507            Apple iPhone 6 Plus 16GB Blue       220350.000000
1559        Samsung Galaxy S6 Edge 32GB White       236127.431917
1684          Apple iPhone 15 Plus 64GB White       201314.400000
1733          Apple iPhone 13 Pro 128GB Black       244463.830000
1816                         Samsung Smart TV       242429.100000
1936               Apple iPhone XR 128GB Blue       234876.440000
2031                Apple iPhone 8 16GB Black       237677.270000
2045                 Apple iPhone 6 16GB Blue       216501.020000
2078               Apple iPhone XR 64GB White       213548.220000
2150                Apple iPhone 14 64GB Blue       233047.890000
2153               Apple iPhone XS 256GB Blue       262678.230000
2161               Apple iPhone 13 256GB Blue       248795.859677
2168              Apple iPhone 14 256GB Black       253252.990000
2181               Apple iPhone 13 128GB Blue       410344.510000
2183                Apple iPhone 6 16GB Black       214572.300000
2257             Dell Ultrabook 4GB RAM Black       256596.350000
2258        Alienware Ultrabook 8GB RAM Black       216402.520000
2323              Acer ThinkPad 4GB RAM Black       207666.810000
2327             Apple ThinkPad 4GB RAM Black       211712.598786
2414              Acer ThinkPad 4GB RAM Black       247059.980000
2457                HP Inspiron 8GB RAM Black       208429.210000
2506          Apple iPhone 15 Pro 128GB White       291804.400000
2528           Apple iPhone 8 Plus 64GB White       209264.140000
2544         Apple iPhone 14 Plus 128GB Black       303416.410000
2597                 Apple iPhone X 16GB Blue       204138.400000
2629              Apple iPhone 15 128GB White       233626.320000
2664       Apple iPhone 12 Pro Max 256GB Blue       251174.690000
2720               Apple iPhone 14 128GB Blue       221353.780000
2723         Apple iPhone 15 Plus 128GB White       261775.200000
2783      Apple iPhone 13 Pro Max 128GB White       231398.180000
2848                Apple iPhone 6 16GB White       218404.890000
2973              Apple iPhone 14 256GB White       300374.780000
2977             Lenovo MacBook 4GB RAM Black       212233.000000
3187                Apple iPhone 7 16GB White       203723.340000
3246               Apple iPhone XR 128GB Blue       260406.220000
3280                Apple iPhone 6 16GB Black       224159.470000
3373               Apple iPhone 13 128GB Blue       410344.510000
3374                         Samsung Smart TV       227832.179032
3382          Apple iPhone 14 Pro 128GB White       222786.720000
3447          Alienware Gaming 8GB RAM Silver       218988.470000
3449      Apple iPhone 12 Pro Max 128GB Black       233051.750547
3480              Apple iPhone 14 256GB Black       253253.000000
3549      Apple iPhone 11 Pro Max 256GB White       252639.300000
3705      Apple iPhone 15 Pro Max 128GB White       282113.770000
3711                 Apple iPhone X 32GB Blue       210618.950000
3800          Apple iPhone XS Max 256GB White       225472.740000
3824               Samsung Android TV Premium       258522.714136
3903           Apple iPhone 12 Pro 64GB Black       211849.000000
4001                 Apple iPhone X 16GB Blue       238760.020000
4007               Apple iPhone XR 128GB Blue       260406.220000
4013           Apple iPhone 13 Pro 64GB Black       252216.760000
4148           Lenovo VivoBook 4GB RAM Silver       281012.180000
4155              Apple iPhone 16 128GB Black       231187.830000
4162          Alienware Gaming 8GB RAM Silver       218988.470000
4222       Apple iPhone 13 Pro Max 128GB Blue       316731.810000
4257             MSI Ultrabook 8GB RAM Silver       204970.550000
4272         Apple iPhone 14 Plus 128GB Black       223760.870000
4314                Apple iPhone XR 64GB Blue       250018.220000
4318           Apple iPhone XS Max 128GB Blue       204006.627255
4334                       LG OLED TV Premium       234409.140000
4416                       LG OLED TV Premium       251062.950000
4459                         LG 4K TV Premium       300102.680000
4500      Apple iPhone 11 Pro Max 256GB White       252639.300000
4520                         LG 4K TV Premium       287334.400000
4560          Apple iPhone 14 Pro 128GB White       245702.950000
4592            Apple iPhone 8 Plus 64GB Blue       216876.158706
4685           Apple iPhone 7 Plus 32GB White       239273.000000
4703         Samsung Galaxy Note 9 64GB Black       208210.590000
4705           Apple iPhone 14 Pro 64GB White       246107.000000
4708              Apple iPhone 15 128GB White       204195.610000
4815             ASUS Inspiron 4GB RAM Silver       221809.010000
4837          Apple iPhone XS Max 256GB Black       232838.327931
4900           Apple iPhone 7 Plus 32GB White       243088.520000
4926                         LG 4K TV Premium       302960.800000
4975      Apple iPhone 13 Pro Max 256GB Black       265660.804552
4978                Apple iPhone X 32GB White       218365.159018
5147             Acer Pavilion 8GB RAM Silver       214183.880000
5171            Apple iPhone 8 Plus 16GB Blue       203034.460663
5172             Lenovo MacBook 4GB RAM Black       200954.220000
5236                Apple iPhone 8 64GB White       205782.040000
5260             Samsung Galaxy S6 64GB White       223321.280000
5312         Apple iPhone 13 mini 256GB White       309508.500000
5315                HP Inspiron 8GB RAM Black       209381.470000
5353              ASUS Pavilion 4GB RAM Black       243811.660000
5441           Apple iPhone 6 Plus 32GB White       227028.600583
5508          Apple iPhone 15 Plus 64GB White       201314.400000
5513            Apple iPhone 11 Pro 64GB Blue       287514.670000
5518         Apple iPhone 14 Plus 128GB Black       256011.520000
5539              Apple iPhone 14 256GB Black       272153.000000
5561                                 LG 4K TV       238554.000000
5632         Apple iPhone 13 mini 128GB White       334932.291127
5676      Apple iPhone 13 Pro Max 128GB White       264749.590000
5712           Alienware Gaming 8GB RAM Black       210283.150000
5770               Apple iPhone 5s 16GB Black       219778.440000
5782          Apple iPhone 15 Pro 128GB White       237513.520000
5854                Apple iPhone 15 64GB Gold       262527.620000
5897                Apple iPhone 6 16GB Black       224159.470000
5936                 Apple iPhone 7 16GB Blue       215609.001088
5995                Apple iPhone X 32GB White       218365.159018
6025             ASUS Ultrabook 8GB RAM Black       205287.740000
6129              Apple Gaming 8GB RAM Silver       240130.560000
6149             Acer Pavilion 8GB RAM Silver       233350.010000
6151          Apple iPhone 13 Pro 128GB Black       244463.830000
6175         Alienware Inspiron 4GB RAM Black       209726.870000
6183           Lenovo VivoBook 4GB RAM Silver       284041.960000
6275           Apple iPhone 7 Plus 16GB White       234092.520000
6368             ASUS Ultrabook 8GB RAM Black       223131.550000
6442                 Apple iPhone 6 16GB Blue       284354.740000
6550           Apple iPhone XS Max 64GB Black       222416.780000
6638               MSI Inspiron 8GB RAM Black       208698.510000
6665         Apple iPhone 14 Plus 128GB Black       256011.520000
6925            Apple iPhone 11 Pro 64GB Blue       276889.090000
6973         Alienware Inspiron 4GB RAM Black       262934.790000
6982            Apple iPhone 8 Plus 16GB Blue       202432.700000
7032              Apple iPhone 14 256GB White       253445.100000
7071                Apple iPhone 8 64GB White       200155.956215
7135                                 LG 4K TV       245965.020000
7266                 Apple iPhone X 16GB Blue       238760.000000
7292               MSI Inspiron 4GB RAM Black       235043.460000
7368            Apple iPhone 6 Plus 16GB Blue       244300.620000
7378              Acer ThinkPad 4GB RAM Black       200486.430000
7387                         LG 4K TV Premium       287334.400000
7389             Apple Pavilion 4GB RAM Black       227739.480000
7441           Apple iPhone 7 Plus 32GB White       239272.950000
7482                 Apple iPhone X 32GB Blue       204825.900000
7485                         LG 4K TV Premium       287334.400000
7497             Samsung Galaxy S6 16GB White       208432.220000
7500          Apple iPhone 13 Pro 128GB Black       289730.480000
7525             Apple ThinkPad 4GB RAM Black       203132.080000
7530           Apple iPhone 8 Plus 64GB White       251677.450000
7542              Apple iPhone 15 128GB White       257657.530000
7587       Apple iPhone 13 Pro Max 128GB Blue       267246.550000
7592         Apple iPhone 13 mini 128GB White       334932.291127
7743             Dell Ultrabook 4GB RAM Black       256596.350000
7965              Apple Gaming 8GB RAM Silver       245284.150000
8148           Apple iPhone XS Max 128GB Blue       212558.590000
8196       Apple iPhone 13 Pro Max 128GB Blue       316731.810000
8201                 Apple iPhone 7 16GB Gold       264637.548212
8204              Dell Pavilion 4GB RAM Black       242116.670000
8210      Apple iPhone 13 Pro Max 128GB White       316371.160291
8337                                 LG 4K TV       245965.020000
8364                 Apple iPhone X 32GB Blue       210618.950000
8391           Apple iPhone 12 Pro 64GB Black       248519.573956
8425              Apple iPhone 11 128GB Black       200253.908600
8575               MSI Inspiron 4GB RAM Black       216247.050000
8617      Apple iPhone 15 Pro Max 256GB White       265408.480000
8630            Apple iPhone 15 Pro 64GB Blue       309077.730000
8634                       LG OLED TV Premium       234409.000000
8726               Apple iPhone XR 64GB White       215006.297970
8785               Samsung Android TV Premium       258522.714136
8786          Samsung Galaxy Note 5 16GB Gold       204938.110000
8952      Apple iPhone 14 Pro Max 128GB White       249342.110000
8990             Apple ThinkPad 4GB RAM Black       203132.080000
9040                 Apple iPhone 7 16GB Gold       264637.548212
9070                         LG 4K TV Premium       287334.400000
9089           Apple iPhone XS Max 64GB Black       218925.680000
9093                Apple iPhone 8 16GB Black       237677.270000
9124                Apple iPhone 6 32GB Black       206713.040000
9169              Dell Pavilion 4GB RAM Black       239534.090000
9329                                 LG 4K TV       251527.090000
9372          Apple iPhone 14 Pro 128GB White       238538.496038
9487              ASUS Pavilion 4GB RAM Black       243811.660000
9553                         Samsung Smart TV       227832.179032
9565                 Apple iPhone 7 16GB Gold       204477.690000
9589          Apple iPhone 14 Plus 64GB White       209487.900000
9609       Apple iPhone 11 Pro Max 64GB White       232240.260000
9636       Samsung Galaxy S23 Ultra 64GB Blue       220486.250161
9670      Apple iPhone 13 Pro Max 256GB White       309308.784240
9716             Apple Pavilion 4GB RAM Black       230407.710000
9887           Apple iPhone 6 Plus 32GB Black       200983.490000
9898               Apple iPhone XR 128GB Blue       234876.440000
9909               Apple iPhone 14 128GB Blue       253257.500000
9929              Dell Pavilion 4GB RAM Black       239534.090000
10077               Apple iPhone 8 16GB Black       237677.270000
10154                Apple iPhone X 64GB Blue       201890.414098
10174      Apple iPhone 12 Pro Max 128GB Blue       229562.050000
10409             Apple iPhone 11 256GB White       222801.820000
10575          Apple iPhone 6 Plus 64GB White       229711.150000
10598            Dell Ultrabook 4GB RAM Black       253859.320000
10602      Apple iPhone 12 Pro Max 64GB White       211096.042246
10628               Apple iPhone 13 64GB Blue       240533.808288
10673                Apple iPhone X 32GB Blue       210618.950000
10681      Apple iPhone 13 Pro Max 128GB Blue       400625.000000
10708        Apple iPhone 13 mini 128GB Black       315743.830000
10735               Apple iPhone 6 16GB Black       248524.380000
10749        Apple iPhone 13 mini 128GB Black       266412.940000
10779               Apple iPhone X 32GB White       218365.159018
10789              Apple iPhone 12 64GB Black       234820.944294
10919           Samsung Galaxy S20 64GB White       215424.610000
11056     Apple iPhone 12 Pro Max 256GB White       228985.110000
11110              Apple iPhone XS 64GB Black       267572.360000
11112                      LG OLED TV Premium       256740.300000
11128           Apple iPhone 11 Pro 64GB Blue       218906.910000
11134             Apple iPhone 11 128GB Black       200253.908600
11207      Samsung Galaxy Note 21 128GB Black       202583.710000
11237     Apple iPhone 12 Pro Max 256GB White       228985.110000
11263               Apple iPhone 8 16GB Black       233946.640000
11282          Apple iPhone 11 Pro 128GB Blue       209887.510000
11286          Apple iPhone 12 Pro 64GB Black       267961.910000
11302                        Samsung Smart TV       242429.100000
11376     Apple iPhone 12 Pro Max 128GB Black       213400.750000
11390              Apple iPhone 5s 16GB Black       213733.450000
11429            Dell ThinkPad 8GB RAM Silver       215691.450000
11436          Apple iPhone 6 Plus 32GB Black       235070.040000
11441           Apple iPhone 8 Plus 64GB Blue       208770.340000
11502               HP Inspiron 8GB RAM Black       213017.270000
11514          Apple iPhone 12 Pro 64GB Black       248519.573956
11520     Apple iPhone 13 Pro Max 256GB Black       265660.804552
11524             Dell Pavilion 4GB RAM Black       242116.670000
11529              Apple iPhone 16 64GB White       251530.000000
11535          Apple iPhone 7 Plus 32GB White       239272.950000
11543              Apple iPhone XS 64GB Black       241340.030000
11648             Samsung Galaxy S8 16GB Blue       201060.590000
11697              Apple iPhone XS 64GB White       208787.480000
11700                        LG 4K TV Premium       296261.380000
11829         Apple iPhone 14 Pro 256GB White       241623.230000
11865         Apple iPhone 14 Pro 256GB White       241623.230000
11900         Apple iPhone 14 Pro 256GB White       241623.230000
11925         Apple iPhone 13 mini 256GB Blue       209340.160000
11954           Apple iPhone 11 Pro 64GB Blue       203704.670000
12027              Apple iPhone 12 64GB White       206571.793049
12047             Apple Aspire 4GB RAM Silver       248812.920000
12062             Apple iPhone 13 128GB Black       297992.685828
12086              Apple iPhone XR 64GB Black       270043.580000
12091         Apple iPhone XS Max 256GB White       225472.740000
12100              Apple iPhone 5s 16GB White       200990.780000
12173             Apple iPhone XS 128GB White       228762.050000
12235           Apple Ultrabook 8GB RAM Black       235452.620000
12390               HP Inspiron 8GB RAM Black       220646.440000
12566        Alienware ThinkPad 8GB RAM Black       229411.870000
12665             Apple Gaming 8GB RAM Silver       240130.560000
12734      Apple iPhone 12 Pro Max 64GB Black       202178.340000
12794              Apple iPhone 12 64GB Black       234820.944294
12808           Apple iPhone 6 Plus 16GB Blue       244300.620000
12836      Apple iPhone 14 Pro Max 64GB White       200620.150000
12905       Apple iPhone 13 Pro Max 64GB Blue       261144.180000
12935               HP Inspiron 8GB RAM Black       208429.210000
12956           Lenovo ThinkPad 4GB RAM Black       212547.750000
13000     Apple iPhone 14 Pro Max 128GB White       217931.630000
13048        Apple iPhone 13 mini 256GB White       280641.250000
13090               Apple iPhone 16 64GB Gold       314005.557879
13095         Apple iPhone 13 mini 64GB Black       217468.820000
13132          Apple iPhone 6 Plus 32GB Black       235070.040000
13136           Apple iPhone 6 Plus 16GB Blue       216891.140000
13143       Alienware Ultrabook 8GB RAM Black       208533.340000
13169          Apple iPhone 15 Pro 128GB Blue       244003.770000
13184                Apple iPhone X 64GB Blue       201630.770000
13267               Apple iPhone 6 16GB Black       220641.020000
13323           Apple iPhone 8 Plus 64GB Blue       208770.340000
13404               Apple iPhone 8 16GB Black       273623.700000
13410           Apple iPhone 6 Plus 32GB Blue       203839.820000
13414         Apple iPhone 11 Pro 128GB Black       263855.180000
13563          Apple iPhone 6 Plus 32GB Black       235070.040000
13682               Apple iPhone 6 16GB White       245259.580000
13758            Dell ThinkPad 8GB RAM Silver       215691.450000

In [38]:
Q1 = df["original_price_inr"].quantile(0.25)
Q3 = df["original_price_inr"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

In [39]:
upper_limit

np.float64(189000.70880503143)

In [40]:
mask = df["original_price_inr"] > upper_limit


df.loc[mask, "original_price_inr"] = df.loc[mask, "product_mean_price"]

df.drop(columns=["product_mean_price"], inplace=True)

In [41]:
df.shape

(1122000, 34)

Question 10
Payment methods contain inconsistent naming: 'UPI/PhonePe/GooglePay', 'Credit Card/CREDIT_CARD/CC', 'Cash on Delivery/COD/C.O.D'. Standardize payment method categories and create a clean categorical hierarchy.

In [42]:
df['payment_method'].value_counts()

payment_method
UPI            382356
COD            321262
Credit Card    171396
Debit Card     139490
Net Banking     64620
Wallet          22678
BNPL            20198
Name: count, dtype: int64

In [43]:
df.shape

(1122000, 34)

In [44]:
df['festival_name'] = df['festival_name'].fillna('No Festival')

In [45]:
df['delivery_charges'] = df['delivery_charges'].fillna(0)

In [46]:
df['customer_age_group'] = df['customer_age_group'].fillna('Unknown')

In [47]:
df["customer_rating"].value_counts()

customer_rating
4.5    597440
5.0    200797
4.0    197324
3.5     79756
3.0     46683
Name: count, dtype: int64

In [48]:
df['transaction_id'].nunique()

1122000

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1122000 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1122000 non-null  object
 1   order_date              1122000 non-null  datetime64[ns]
 2   customer_id             1122000 non-null  object
 3   product_id              1122000 non-null  object
 4   product_name            1122000 non-null  object
 5   category                1122000 non-null  object
 6   subcategory             1122000 non-null  object
 7   brand                   1122000 non-null  object
 8   original_price_inr      1122000 non-null  float64
 9   discount_percent        1122000 non-null  float64
 10  discounted_price_inr    1122000 non-null  float64
 11  quantity                1122000 non-null  int64
 12  subtotal_inr            1122000 non-null  float64
 13  delivery_charges        1122000 non-null  float64
 14  final_amount_inr        1122000 non-null  float64
 15  customer_city           1122000 non-null  object
 16  customer_state          1122000 non-null  object
 17  customer_tier           1122000 non-null  object
 18  customer_spending_tier  1122000 non-null  object
 19  customer_age_group      1122000 non-null  object
 20  payment_method          1122000 non-null  object
 21  delivery_days           1122000 non-null  Int64
 22  delivery_type           1122000 non-null  object
 23  is_prime_member         1122000 non-null  bool
 24  is_festival_sale        1122000 non-null  bool
 25  festival_name           1122000 non-null  object
 26  customer_rating         1122000 non-null  float64
 27  return_status           1122000 non-null  object
 28  order_month             1122000 non-null  int64
 29  order_year              1122000 non-null  int64
 30  order_quarter           1122000 non-null  int64
 31  product_weight_kg       1122000 non-null  float64
 32  is_prime_eligible       1122000 non-null  bool
 33  product_rating          1122000 non-null  float64
dtypes: Int64(1), bool(3), datetime64[ns](1), float64(9), int64(4), object(16)
memory usage: 278.2+ MB

In [50]:
df.to_csv("amazon_india_2015_to_2025_cleaned.csv", index=False)

In [51]:
df.dtypes

transaction_id                    object
order_date                datetime64[ns]
customer_id                       object
product_id                        object
product_name                      object
category                          object
subcategory                       object
brand                             object
original_price_inr               float64
discount_percent                 float64
discounted_price_inr             float64
quantity                           int64
subtotal_inr                     float64
delivery_charges                 float64
final_amount_inr                 float64
customer_city                     object
customer_state                    object
customer_tier                     object
customer_spending_tier            object
customer_age_group                object
payment_method                    object
delivery_days                      Int64
delivery_type                     object
is_prime_member                     bool
is_festival_sale                    bool
festival_name                     object
customer_rating                  float64
return_status                     object
order_month                        int64
order_year                         int64
order_quarter                      int64
product_weight_kg                float64
is_prime_eligible                   bool
product_rating                   float64
dtype: object

In [52]:
amazon_raw = pd.read_csv("amazon_india_complete_2015_2025.csv")

In [53]:
comparison = pd.DataFrame({
    'Before_Cleaning': amazon_raw.isna().sum(),
    'After_Cleaning': df.isna().sum()
})
comparison

                        Before_Cleaning  After_Cleaning
transaction_id                        0               0
order_date                            0               0
customer_id                           0               0
product_id                            0               0
product_name                          0               0
category                              0               0
subcategory                           0               0
brand                                 0               0
original_price_inr                    0               0
discount_percent                      0               0
discounted_price_inr                  0               0
quantity                              0               0
subtotal_inr                          0               0
delivery_charges                  90201               0
final_amount_inr                      0               0
customer_city                         0               0
customer_state                        0               0
customer_tier                         0               0
customer_spending_tier                0               0
customer_age_group               135315               0
payment_method                        0               0
delivery_days                         0               0
delivery_type                         0               0
is_prime_member                       0               0
is_festival_sale                      0               0
festival_name                    777736               0
customer_rating                  341696               0
return_status                         0               0
order_month                           0               0
order_year                            0               0
order_quarter                         0               0
product_weight_kg                     0               0
is_prime_eligible                     0               0
product_rating                        0               0